# Generated by Django 3.2.7 on 2021-09-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='creator',
        ),
    ]
